# NOTE: update this with your service name
service: create-cognito-user-pool

# Create an optimized package for our functions
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables
  - aws-cognito-idp-userpool-domain

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: us-east-1
  # To load environment variables externally
  # rename env.example to .env and uncomment
  # the following line. Also, make sure to not
  # commit your .env.
  #
  #environment:
  #  sampleEnvVar: ${env:SAMPLE_ENV_VAR}

custom:
  stage: ${opt:stage, self:provider.stage}
  poolName: ${self:custom.stage}-user-pool

resources:
  - ${file(resources/cognito-user-pool.yml)}

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: hello
          method: get

  preSignUp:
    handler: pre-signup.main
    events:
      - cognitoUserPool:
          pool: MyUserPool
          trigger: PreSignUp
